<!DOCTYPE html>
<title>Raceroom Reulst Embedded League Display</title>
<html>
<body>
<h1>{{leagueinfo.info.LeagueName}}</h1>
<table id="servertable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
						<th>
						Server
						</th>
						<th>
						Date
						</th>
						<th>
						Track
						</th>
						<th>
						Winner
						</th>
					</tr>
					</thead>
<tbody>
	{% for data in leagueinfo.servers %}
	<tr>
	<td><a href="server/{{data.ID}}.html">{{data.Server}}</a></td>
	<td>{{data.Date}}</td>
		<td>{{data.Track}}</td>
		
		<td><a class="green" href="drivers/{{data.Winner.PlayerID}}.html">{{data.Winner.FullName}}</a></td>

	</tr>
	{%endfor%}
	</tbody>
</table>
<h2>Drivers</h2>
<table id="drivertable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
						<th>
						Position
						</th>
						<th>
						Driver
						</th>
						<th>
						Points
						</th>
					</tr>
					</thead>
					<tbody>
	{% for key,data in leagueinfo.rankings %}
	<tr>
	<td>{{data.pos}}</td>
	<td><a class="green" href="drivers/{{data.ID}}.html">{{key}}</a></td>
	<td>{{data.points}}</td>
	</tr>
	{%endfor%}
	</tbody>
	</table>

</body>
</html>