<!-- page content -->

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>{{data.driver.FullName}}<small>Driver Report</small></h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="#">Settings 1</a>
                          </li>
                          <li><a href="#">Settings 2</a>
                          </li>
                        </ul>
                      </li>
                      <li><a class="close-link"><i class="fa fa-close"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">

                    <div class="col-md-3 col-sm-3 col-xs-12 profile_left">

                      <div class="profile_img">

                        <!-- end of image cropping -->
                        <div id="crop-avatar">
                          <!-- Current avatar -->
						  {% if data.driver.registered %}
                          <img class="img-responsive avatar-view" src="{{data.driver.avatar}}" alt="Avatar" title="Change the avatar">
						  <a class="green" target="_blank" href="http://steamcommunity.com/profiles/{{data.driver.steamID}}">Steam Profile</a>
						  {% endif %}
                          

                          <!-- Loading state -->
                          <div class="loading" aria-label="Loading" role="img" tabindex="-1"></div>
                        </div>
                        <!-- end of image cropping -->

                      </div>
                      <h3>{{data.driver.FullName}}</h3>
						  {% if not data.driver.registered %}
					  <p class="small">Unregistered</p>
					  {%endif%}

                      <ul class="list-unstyled user_data">
					  <li><i class="fa fa-automobile user-profile-icon"></i> Favourite Car <br> {{data.favcar}}
                        </li>
						<hr>
                        <li><i class="fa fa-trophy user-profile-icon"></i> {{data.wins}} Wins
                        </li>
                        <li>
                          <i class="fa fa-list-ol user-profile-icon"></i> {{data.podiums}} Podiums
                        </li>
						<li>
                          <i class="fa fa-star-o user-profile-icon"></i> {{data.pole}} Pole Laps
                        </li>
						<li>
                          <i class="fa fa-flag-checkered user-profile-icon"></i> {{data.racestarts}} Race Starts
                        </li>
						<li>
                          <i class="fa fa-ban user-profile-icon"></i> {{data.dnf}} Retirements
                        </li>

                        
                      </ul>
					  {% if profile %}
						{% if data.driver.registered %}
                      <a class="btn btn-success"><i class="fa fa-edit m-right-xs"></i>Edit Profile</a>
                      <br />
					  {%endif%}
					  {%endif%}

                      

                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-12">

                      <div class="profile_title">
                        <div class="col-md-6">
                          <h2>User Activity Report</h2>
                        </div>
                        <div class="col-md-6">
                          <div id="reportrange" class="pull-right" style="margin-top: 5px; background: #fff; padding: 5px 10px; border: 1px solid #E6E9ED">
                           <span>Recent Events</span>
                          </div>
                        </div>
                      </div>
                      <!-- start of user-activity-graph -->
                      <table class="table table-hover">
  <thead>
  <tr>
    <th>Server</th>
	<th>Track</th>
	<th>Car</th>
	<th>Position</th>
  </tr>
 </thead>
<tbody>
			{% for content in data.servers %}
				
				<tr><td><a href="/server/{{content.ServerInfo.ID}}.html">{{ content.ServerInfo.Server }}</a></td><td>{{ content.ServerInfo.Track }}</td><td>{{ content.Car }}</td><td>{{ content.Position }}</td></tr>
			{% endfor %}
			</tbody>
	</table>
                      <!-- end of user-activity-graph -->



                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->