{% include 'head.phtml' %}
<body class="nav-md">
    <div class="container body">
		<div class="main_container">
			{% include 'side_menu.phtml' %}
<div class="right_col" role="main">
{%include 'topmenu.phtml' %}
 <div class="row">
  <div class="col-md-8 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">		
<h2>Servers</h2>
<div class="clearfix"></div>
</div>
<div class="x_content">
<table id="servertable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
						<th>
						Server
						</th>
						<th>
						Date
						</th>
						<th>
						Track
						</th>
					</tr>
					</thead>
<tbody>
	{% for data in serverdata %}
	<tr>
	<td><a href="server/{{data.ID}}.html">{{data.Server}}</a></td>
	<td>{{data.Date}}</td>
		<td>{{data.Track}}</td>

	</tr>
	{%endfor%}
	</tbody>
</table>	
</div>
</div>
</div>
            <div class="col-md-4 col-sm-12 col-xs-12">
              <div class="x_panel">
                <div class="x_title">		
<h2>Drivers</h2>
<div class="clearfix"></div>
</div>
<div class="x_content">
<table id="drivertable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
						<th>
						ID
						</th>
						<th>
						Driver
						</th>
					</tr>
					</thead>
					<tbody>
	{% for data in driverData %}
	<tr>
	<td>{{data.ID}}</td><td><a href="drivers/{{data.ID}}.html">{{data.Fullname}}</a></td>
	</tr>
	{%endfor%}
	</tbody>
	</table>
</div>
</div>
</div>

</div>
<div class="clearfix"></div>
	
{% include 'footer.phtml' %}
 <script src="{{ template }}/vendors/jquery/dist/jquery.min.js"></script>
<!-- Datatables -->
    <script src="/{{ template }}/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/{{ template }}/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script src="/{{ template }}/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>
    <script src="/{{ template }}/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    <script src="/{{ template }}/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>
    <script src="/{{ template }}/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>
    <script src="/{{ template }}/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>
    <script src="/{{ template }}/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/{{ template }}/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/{{ template }}/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/{{ template }}/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="/{{ template }}/vendors/datatables.net-scroller/js/datatables.scroller.min.js"></script>
    <script src="/{{ template }}/vendors/jszip/dist/jszip.min.js"></script>
    <script src="/{{ template }}/vendors/pdfmake/build/pdfmake.min.js"></script>
    <script src="/{{ template }}/vendors/pdfmake/build/vfs_fonts.js"></script>

    <!-- Custom Theme Scripts -->
    <script src="{{ template }}/js/custom.js"></script>

<script>
 {% if driverData|length > 10 %}
 $('#drivertable').dataTable();
 {%endif%}
 {% if serverdata|length > 10 %}
 $('#servertable').dataTable();
 {%endif%}
 
 </script>
 
