<body onload="startTime()" class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="/index.php" class="site_title"><i class="fa fa-home"></i> <span>Main Menu </span></a>
            </div>

            <div class="clearfix"></div>

            <!-- menu profile quick info -->
			{% if profile %}
            <div class="profile">
              <div class="profile_pic">
                <img src="{{profile.avatar}}" alt="..." class="img-circle profile_img">
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{profile.personaname}}</h2>
              </div>
            </div>
			
			{% else %}
			<ul class="nav side-menu">
			                     <li><a href="\?login"><img src="/img/sits_small.png"></a>
                      </li>
					  </ul>
			{%endif%}
            <!-- /menu profile quick info -->

            <br />

            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-home"></i> Servers <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
					{% if profile %}
						<li><a href="#">My Servers<span class="label label-success pull-right">Coming Soon</span></a>
                      </li>
					 {%endif%}
                      <li><a href="#">Ranked<span class="label label-success pull-right">Coming Soon</span></a>
                      </li>
                      <li><a href="#">Unranked<span class="label label-success pull-right">Coming Soon</span></a>
                      </li>
                      <li><a href="#">All<span class="label label-success pull-right">Coming Soon</span></a>
                      </li>
                    </ul>
                  </li>
                  <li><a><i class="fa fa-edit"></i> Drivers <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
					{% if profile %}
					<li><a href="/driver.html">My Driver Record</a>
										 {%endif%}
                      </li>
                     
                    </ul>
                  </li>
                  <li><a><i class="fa fa-desktop"></i> Leagues <span class="fa fa-chevron-down"></span></a>
                    <ul class="nav child_menu">
					{%if profile%}
                      <li><a href="../myleagues.html">My Leagues</a>
                      </li>
					 {%endif%} 
                      <li><a href="../userleagues.html">All Leagues</a>
                      </li>
                     
                    </ul>
                  </li>  
                  </ul>
              </div>
              <div class="menu_section">
                
                <ul class="nav side-menu">
                  <li><a><i class="fa fa-user"></i>My Profile<span class="fa fa-chevron-down"></span></a>
				  <ul class="nav child_menu">
				  {% if not profile %}
                    <li><a href="\?login"><img src="/img/sits_small.png"></a>
                      </li>
					  {%endif%}
					  {% if profile %}
                      <li><a href="#">Edit Profile<span class="label label-success pull-right">Coming Soon</span></a>
                      </li> 
                      <li><a href="#">Contacts<span class="label label-success pull-right">Coming Soon</span></a>
                      </li>
					  
                      <li><a href="?logout">Log Out</a>
					  {% endif %}
                      </li>
                    </ul>
				</li>
                  
                  
                  
                </ul>
              </div>
			 
            </div>
            <!-- /sidebar menu -->

           
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">

          <div class="nav_menu">
            <nav class="" role="navigation">
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
			
              </div>
			 
              <ul class="nav navbar-nav">
			  <li><h1>{{ site_name }}</h1></li>
				
              </ul>
            </nav>
          </div>

        </div>
        <!-- /top navigation -->