<div class="">
            <div class="page-title">
              <div class="title_left">

                <h3>{{pagetitle}}</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
				<form id="genericsearch" name="search" action="../search.php" method="get">
                  <div class="input-group">
				  
                    <input type="text" class="form-control" name="search" placeholder="Search for...">
                    <span class="input-group-btn">
                              <button form="genericsearch" class="btn" value="Submit" name="Submit" type="button">Go!</button>
                    </span>
					
						  
                  </div>
				  </form>
                </div>
              </div>
            </div>
            <div class="clearfix"></div>